name: qa-eval
on: [push, pull_request]
jobs:
  run-evals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run generation & tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_questions.py
          python run_tests.py
          python judge.py
          python generate_report.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: qa-report
          path: qa_report.csv
